
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyCodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: my-code-repo

  MyECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: my-ecr-repo

  MyCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: my-code-build-project
      ServiceRole: arn:aws:iam::176350447910:role/my-code-build-role
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: ECR_REGISTRY
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com
          - Name: ECR_REPO_NAME
            Value: my-ecr-repo

  MyCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: my-code-pipeline
      RoleArn: arn:aws:iam::176350447910:role/my-code-pipeline-role
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                RepositoryName: my-code-repo
                BranchName: master
              RunOrder: 1
        - Name: Dev
          Actions:
            - Name: DevBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: DevArtifact
              Configuration:
                ProjectName: my-code-build-project
              RunOrder: 1
            - Name: DevApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              InputArtifacts:
                - Name: DevArtifact
              OutputArtifacts:
                - Name: DevApproval
              Configuration:
                NotificationArn: arn:aws:sns:us-west-2:176350447910:my-dev-approval-topic
                CustomData: "Please approve the Dev deployment."
              RunOrder: 2
        - Name: QA
          Actions:
            - Name: QABuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: DevArtifact
              OutputArtifacts:
                - Name: QAArtifact
              Configuration:
                ProjectName: my-code-build-project
              RunOrder: 1
